Feature branch
Tahirbhalli/Positioning-and-floating pull request #2
Opened 2020-01-30 12:39 UTC by Tahirbhalli

2020-01-30 13:21 UTC, rOluochKe requested changes
Hello @Tahirbhalli and @adamclasic 

### You have done a really good job so far, however, there are issues you need to work on for your project to be marked completed.
- Write a more descriptive pull request [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- Improve your readme file, make it better [check this guide](https://github.com/microverseinc/readme-template)
- A floating sidebar on the right is missing from your project, refer to the origin [website](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)
![sidebar-missing](https://user-images.githubusercontent.com/8114528/73452607-4243cf00-437b-11ea-92e0-812cb0afc266.PNG)
- In your navigation, use `nav` not `div ` and make use of `section, article, sidebar` in this project. Avoid segmenting using divs
- Validate your html code and rectify the error, [use this tool](https://validator.w3.org/#validate_by_upload)
- Configure your code with linter [check this guide](https://github.com/microverseinc/linters-config/tree/master/css)

### Make these changes and resubmit for another code review. I wish you all the best in your submission.
-If you are having challenges, reach out to me @rOluochKe

2020-01-30 19:02 UTC, MauricioRobayo requested changes
Hi, this is coming into place, really great job!

But there are still some issues that are not solved:

- [x] Write a more descriptive pull request - you can edit the pull request description.
- [x] It should have a fixed position footer (it sticks to the bottom part of the screen).
- [ ] It uses [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the rightmost side.
---
![image](https://user-images.githubusercontent.com/2121481/73480771-8aa5c180-4368-11ea-985b-d4230e23b25b.png)
---
**[OPTIONAL]**
- [ ] You can use then `nav` tag for the navigation bar inside the `header` and the `main` tag for the main section.

Status: **Request changes**.

2020-01-30 19:02 UTC, MauricioRobayo commented on index.html
> +                <div class="header-cont">
This could be a `nav` tag.

2020-01-30 19:02 UTC, MauricioRobayo commented on index.html
> +            <section>
This could be a `main` tag.

2020-01-30 19:17 UTC, adamclasic commented
very good review @MauricioRobayo 
we'll work on that, Thank you.

2020-01-31 23:48 UTC, MauricioRobayo requested changes
Hi, it is almost there, but 😣:

- [ ] Still missing the `aside` tag for Editor's picks section on the rightmost side. See the screenshot from the previous review.
- [ ] There is an issue on wider screens with the alignment of `.grid-container` at the `footer`, take a look at this screenshot (I apologize, didn't notice this before):
![image](https://user-images.githubusercontent.com/2121481/73581669-00d52180-4458-11ea-9d91-dc519c986442.png)

The project is looking great! Keep up the hard work 💪.

Status: **Request changes**.

2020-01-31 23:48 UTC, MauricioRobayo commented on styles/style.css
> +  margin-left: 2rem;
Try setting the margin to the left and right to `auto`, for example: `margin: 0 auto`. That might solve the issue with the misalignment on wider screens. Take a look at this: https://www.w3schools.com/css/css_align.asp

2020-08-21 10:21 UTC, closed without merging